### PR TITLE
Added Windows support, added missing color modes

### PR DESCRIPTION
**Pull request by jneumaier**
Thanks for your project! I would like to contribute some additional features.

### CODE REVIEW

**Comment by jneumaier** [comment]
Sorry for the mixed pull request, I messed this up a little and forgot to branch earlier.
By the way, please update the pip package, it is a little outdated.

My example has a minor mistake, 4 should be 2, but does not really matter:
colctl --mode spinner --color0 9,33,71 --color1 2,7,15 --color_count **4** --animation_speed 2

**Comment by jneumaier** [comment]
And maybe you do not like the mode names, please feel free to change. I took the names from this Node.js implementation:
[Node.js source](https://github.com/yetzt/node-krkn/blob/master/index.js)

I did not see your protocol implementation using different mode names.

**Comment by jneumaier** [comment]
Now I got it consistent I hope. Reverted the names again, should be good with yetzt's pull request [](https://github.com/KsenijaS/krakenx/pull/6)

**Comment by KsenijaS** [comment]
Thank you for your contribution!
Sadly there is conflict with this merge. It would be great if you could repost your patches.
 
Thanks :)

**Comment by jneumaier** [comment]
I merged the pull requests you added and also added the marquee mode. Maybe it is not working correctly (only using two colors) but I think it can be fixed from here if necessary. I like to use it myself :-)

**Comment by jneumaier** [comment]
You may also add Windows support in the github project description but of course this is not the primary project goal.

Please don't forget to update the pypi pip package, it is from from [June 2017](https://pypi.org/project/krakenx/#history)

**Comment by thevik** [comment]
Thanks for implementing this jneumaier! Can't wait for the merge :3

**Comment by jneumaier** [comment]
@thevik 
My pleasure. We all suffer from CAM software :-)

Please feel free to try / beta test on my repository [jneumaier/krakenx](https://github.com/jneumaier/krakenx):

`
git clone https://github.com/jneumaier/krakenx.git
cd krakenx
python -m pip install -e .
`

This will install the pip package from source. Uninstall with `python -m pip uninstall krakenx` if you want to reinstall the maintained when available.

**Pull request merged**
