### PR TITLE
+speed, color modes

### PR DESCRIPTION
**Pull request by yetzt**
second byte in mode is speed, missing modes discovered by testing.

### CODE REVIEW

**Comment by KsenijaS** [comment]
Hi,

Thank you for your contribution, I tried to implement new modes but for some reason text color cannot be set. Did you have the same issue?

Thanks

**Comment by yetzt** [comment]
text color does not work for some modes when ring and text are not set separately. i will share my findings later. :)

**Comment by yetzt** [comment]
[here you go](https://gist.github.com/yetzt/25913ab518b5ee94860ef72595fdf605)

**Comment by jneumaier** [comment]
@yetzt Thank you very much. A lot of this (all?) should be also be implemented by now.

**Pull request merged**
